### ISSUE TITLE
Usage instructions in the README need updating

### ISSUE THREAD

**Issue by catherinewatkinson** [Dapid/tmscoring#3]
I assume the code has been updated since the README was written as I had to make a couple of very small changes to get the example code running.

in line 1: TMscore -> TMscoring

in final line: alignment.write(outputfile='aligned.pdb', append=True) -> alignment.write(outputfile='aligned.pdb', appended=True)

**Comment by Dapid** [comment]
Thanks! Just sloppy documentation on my part.
