### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (4,427) (4,432)  - Different sequence legnth?

### ISSUE THREAD

**Issue by gavieira** [Dapid/tmscoring#4]
Hi,

I've been trying to obtain rmsd values for two sequences, but have been getting this error:

ValueError: operands could not be broadcast together with shapes (4,427) (4,432)

The two pdb files have different sequence length. I assume that is the reason I'm getting this error, even though the TMscore web server still manages to compute RMSD/TM-scores for these sequences (available in [pdbs.zip](https://github.com/Dapid/tmscoring/files/7217890/pdbs.zip)).

Any tips on how to run this module it using sequences with differing lenghts?

Thank you very much for the help and the program!

**Comment by Dapid** [comment]
By default, we use the index, which requires the same numbering. You can  run it in "alignment" mode, where we do a sequence alignment:

```
alignment = tmscoring.TMscoring('2pa6_eno_arch.pdb', 'BAA81473.1.B99990001.pdb', mode='align')
```

That works, and gives a TM score of 0.647 and RMSD of 3.076.

Why is that mode not documented? I wonder the same thing, I must have missed it.

It would be reasonable to make indexing mode work for sequences of different size, keeping only the ones that match. That should be easy enough to add.
